apiVersion: email.hermes.sender/v1
kind: EmailSenderConfig
metadata:
  labels:
    app.kubernetes.io/name: hermes-mail-sender-operator
    app.kubernetes.io/managed-by: kustomize
  name: emailsenderconfig-sample
spec:
  # TODO(user): Add fields here
